language: c++
submodules:
  - g++
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
branches:
  only:
    - gbolt-1.0
git:
  submodules: true
before_script:
  # Export CC and CXX to tell cmake which compiler to use
  - export CC=gcc-7
  - export CXX=g++-7
  - ./scripts/build.sh
script:
  - ./scripts/Compound_422.sh
